id: b81190ea93bf4a979974c5e7f67a510f
initial_creation_type: ebook
source_metadata:
  title: test
  subtitle: ''
  authors:
  - test
  collection: ''
  publisher: ''
  id: test
  cover: tmpwx_mk8eo.jpg
  credit: tmp4nym39he.jpg
