id: b81190ea93bf4a979974c5e7f67a510f
initial_creation_type: ebook
created_at: 8/04/2021
last_modified_at: 25/11/2021
source_metadata:
  title: test
  subtitle: ''
  authors:
  - test
  collection: ''
  publisher: ''
  id: test
  cover: tmpwx_mk8eo.jpg
  credit: tmp4nym39he.jpg
